### ISSUE TITLE
Missing dependency to storybook-i18n/preview

### ISSUE THREAD

**Issue by teamoo** [stevensacks/storybook-react-intl#1]
In https://github.com/stevensacks/storybook-react-intl/blob/main/preset.js you require `storybook-i18n/preview`, but didn't add a dependency in your package.json. Thus, users of your package receive an error, that the module `storybook-i18n` was not fount.

**Comment by stevensacks** [comment]
I believe this was fixed in [this PR](https://github.com/stevensacks/storybook-react-intl/pull/4). Please let me know if it works for you.

**Comment by teamoo** [comment]
Yes thanks!
