### ISSUE TITLE
initialGlobals does not work

### ISSUE THREAD

**Issue by danilofuchs** [stevensacks/storybook-react-intl#14]
With initialGlobals:

![image](https://github.com/user-attachments/assets/9de7de4c-d3fd-4cd6-9322-2335983cc423)

With globals:
![image](https://github.com/user-attachments/assets/d3b3ecfe-2895-4c45-806f-44403477ddb6)

react-intl.ts
```typescript
import en from "../src/lang/en.json";
import ptBR from "../src/lang/pt-BR.json";

const locales = ["pt-BR", "en"];

const messages = {
  "pt-BR": ptBR,
  en: en,
};

export const reactIntl = {
  defaultLocale: "pt-BR",
  locales,
  messages,
};

```

preview.ts
```typescript
  parameters: {
    reactIntl,
  },
  initialGlobals: {
    locale: reactIntl.defaultLocale,
    locales: {
      "pt-BR": { title: "Português", left: "🇧🇷" },
      en: { title: "English", left: "🇺🇸" },
    },
  },
```

**Comment by stevensacks** [comment]
Whether you use initialGlobals or globals depends on the version of Storybook you are running. As of 8.2, you can use either. Before 8.2, you can only use globals. As of 9.x, you can no longer use globals.
