### ISSUE TITLE
Support react-intl v7

### ISSUE THREAD

**Issue by michaelfaith** [stevensacks/storybook-react-intl#15]
`react-intl` recently updated to a new major version.  The only real aspect of it that's breaking is the new min version of TypeScript (5.0).  So, it should be pretty straightforward to support. 
https://github.com/formatjs/formatjs/releases/tag/react-intl%407.0.0

**Comment by stevensacks** [comment]
Fixed and released in [v3.2.1](https://github.com/stevensacks/storybook-react-intl/releases/tag/v3.2.1)
