### ISSUE TITLE
locale is used from globals rather than parameters

### ISSUE THREAD

**Issue by teamoo** [stevensacks/storybook-react-intl#2]
In https://github.com/stevensacks/storybook-react-intl/blob/main/src/preset/preview.tsx you use this call:
`const [{locale}] = useGlobals();`
While this is perfectly fine, the README does not mention that this package needs a global to be set. I would suggest that you 

- either add this prerequisite to define this global (as mentioned in the [official Storybook Docs](https://storybook.js.org/docs/react/essentials/toolbars-and-globals#advanced-usage)) or
- use the locale that is given into the context as defined in your README:
`const locale = context.parameters.locale;`

**Comment by stevensacks** [comment]
Sorry for the delay. I believe this has been fixed by [this PR.](https://github.com/stevensacks/storybook-react-intl/pull/4/commits/e0b567a0b15f0a36c33a8cf0214ab43f5b8a9f7b)

Please let me know if this fixes the issue.

**Comment by stevensacks** [comment]
@teamoo Can you please confirm whether this issue was also fixed? If so, please go ahead and close the issue. :)

**Comment by teamoo** [comment]
No, can't right now, I am not using the package right now and have no setup for that.

**Comment by stevensacks** [comment]
I believe that this was resolved so I’ll close it for now.
