### ISSUE TITLE
Question on imports

### ISSUE THREAD

**Issue by StuartMorris0** [stevensacks/storybook-react-intl#3]
Struggling to get this running with the example.

Looking at the exports from `react-intl` there doesn't appear to be any locale-data folder?

`Cannot find module 'react-intl/locale-data/en'`

**Comment by StuartMorris0** [comment]
Looks like these were deprecated a while ago in react-intl.

https://formatjs.io/docs/react-intl/upgrade-guide-2x
https://formatjs.io/docs/react-intl/upgrade-guide-3x#migrate-to-using-native-intl-apis

**Comment by stevensacks** [comment]
Just so I'm clear, is this an issue with [this section](https://github.com/stevensacks/storybook-react-intl#reactintljs) of the README documentation using a deprecated example?

**Comment by VED-StuartMorris** [comment]
Hey @stevensacks Yes, that part of the readme is a little dated. Not sure on the correct way to implement this now, I believe I had to move for a different approach

**Comment by StuartMorris0** [comment]
Hey @stevensacks Yes, that part of the readme is a little dated. Not sure on the correct way to implement this now, I believe I had to move for a different approach

**Comment by stevensacks** [comment]
I read this on the previous react-intl plugin for Storybook and wasn't aware it was deprecated.

The good news it that particular code is not relevant to how this plugin works, it's for setting up ReactIntl itself outside the scope of this plugin. This plugin hooks up your configured ReactIntl to Storybook so it changes languages, re-renders when the language strings change, etc.

Do you know what the updated code is for setting up ReactIntl so I can update the README to reflect that?

**Comment by StuartMorris0** [comment]
Yeah, so the old lines (top three lines) in the ReactIntl.js file are not needed, but kept the rest. Then in preview have the following...

```
const withInternationalProvider = (Story, context) => {
  const globals = context.globals;
  const {
    parameters: { reactIntl }
  } = context;
  const { messages } = reactIntl;
  const locale = globals.locale ?? 'en';
  return (
    <IntlProvider
      key={locale}
      messages={messages[locale]}
      locale={locale}
      defaultLocale={context.parameters.locale}
    >
      <Story {...context} />
    </IntlProvider>
  );
};
```

Implemented the international provider like above. Then the same as before...

```
export const decorators = [
  withThemeProvider,
  withInternationalProvider,
  withTests({ results, filesExt: '((\\.specs?)|(\\.test?))?(\\.tsx)?$' })
];

export const parameters = {
  reactIntl,
  locale: reactIntl.defaultLocale,
  locales: {
    en: 'English',
    de: 'Deutsche'
  },
... 
```

**Comment by stevensacks** [comment]
My [implementation of the provider](https://github.com/stevensacks/storybook-react-intl/blob/main/src/preset/preview.tsx) is slightly more robust than yours, but functionally equivalent (although maybe the `formats` are deprecated?)

Would you be willing to fork this repo and commit a rewrite of [this section](https://github.com/stevensacks/storybook-react-intl#reactintljs) of the README?

**Comment by stevensacks** [comment]
Fixed in latest version
