### ISSUE TITLE
Storybook preview hooks can only be called inside decorators and story functions.

### ISSUE THREAD

**Issue by jbarradas** [stevensacks/storybook-react-intl#7]
Just installed this plugin and configured it according the docs here, but I'm getting this error on the title.

Here is my `preview.js`:
```
import { ThemeProvider } from "@mui/material/styles";
import { addDecorator } from "@storybook/react";
import { withThemes } from "@react-theming/storybook-addon";
import { RouterContext } from "next/dist/shared/lib/router-context";

import { reactIntl } from "./reactIntl";
import getTheme from "../src/theme/getTheme";
import themes from "../src/theme";

const providerFn = ({ theme, children }) => {
  // https://github.com/react-theming/storybook-addon/issues/30
  const serialTheme = JSON.parse(JSON.stringify(theme));
  const muiTheme = getTheme(serialTheme);
  return <ThemeProvider theme={muiTheme}>{children}</ThemeProvider>;
};

addDecorator(
  withThemes(
    null,
    Object.values(themes).map((theme) => getTheme(theme.options)),
    { providerFn }
  )
);

export const parameters = {
  nextRouter: {
    Provider: RouterContext.Provider,
  },
  reactIntl,
  locale: reactIntl.defaultLocale,
  locales: {
    nl: "Nederlands",
    en: "English",
    de: "Deutsche",
    fr: "Français",
  },
};

```

Notes:
- I had up upgrade both `react-intl` and `@storybook/react` to comply with minimum required versions.
- In `reactIntl.js`, I've changed the translation file from `.json` to  `.ts` (Not sure if this will be an issue, but I don't think it should matter  for this issue)
- React-Intl is working fine in the application

Has this come up to somebody?
Does anyone know a solution for this, or where to start looking?
Thanks in advance!

**Comment by stevensacks** [comment]
Are you by chance using your own decorator which renders using `<Story/>`? If so, try rendering using `{story()}` and see if that solves it.

**Comment by jbarradas** [comment]
> 

Sorry we suspended these stories for now. Don't have an answer yet. But I'll update when we get back to this.

**Comment by jbarradas** [comment]
Closing for now.
